package com.bossien.flowtreatmentservice.entity;

import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@Data
@Table(name = "users")
@Entity
public class Users {
    @Id
    private Long id;


    private String username;


    private String nickname;

    private String password;

    private Long companyId;

    private String telephone;
    private Byte sex;


    private String email;

    private Byte state;


    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.open_id
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_user
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_date
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.oper_user
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private String operUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.oper_date
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.supporter
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private Byte supporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_type
     *
     * @mbggenerated Tue Apr 24 13:03:04 CST 2018
     */
    private Byte userType;


    private Byte registType;


    private Byte examNum;


    private Byte isRegister;
    @Transient
    private Integer  count ;

    public Users() {

    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, Long companyId) {
        this.id = id;
        this.companyId = companyId;

    }

    public Users(Integer count, Long companyId) {
        this.count = count;
        this.companyId = companyId;

    }

    public Users(Long id, String nickname, String telephone, Long companyId) {
        this.id = id;
        this.nickname = nickname;
        this.companyId = companyId;
        this.telephone = telephone;
    }
}